import { GiftProduct } from "./types";

// A deliberately labelled demo inventory for the hackathon sandbox. Prices,
// availability and delivery promises must be replaced by a connected merchant
// response before a production order is offered.
export const CATALOG: GiftProduct[] = [
  {
    id: "gft_chaibar_box",
    title: "Slow Sunday Chai Box",
    description: "Masala chai, two clay kulhads, nankhatai and a small handwritten note.",
    price: 1499,
    currency: "INR",
    merchant: "Posy demo inventory",
    merchantUrl: "https://posy.getcontios.com",
    category: "food",
    tags: ["chai", "tea", "mom", "dad", "cozy", "foodie", "home", "thoughtful"],
    rating: 4.8,
    deliveryDays: 1,
    source: "demo",
  },
  {
    id: "gft_selfcare_box",
    title: "Quiet Evening Self-care Box",
    description: "Soy candle, bath salts, herbal tea and a soft eye mask. Nothing too fussy.",
    price: 2299,
    currency: "INR",
    merchant: "Posy demo inventory",
    merchantUrl: "https://posy.getcontios.com",
    category: "wellness",
    tags: ["relaxation", "self-care", "mom", "sister", "wife", "cozy", "home", "her"],
    rating: 4.9,
    deliveryDays: 2,
    source: "demo",
  },
  {
    id: "gft_filter_coffee",
    title: "South Indian Filter Coffee Kit",
    description: "Classic steel filter, fresh ground coffee and two dabarah tumblers.",
    price: 1899,
    currency: "INR",
    merchant: "Posy demo inventory",
    merchantUrl: "https://posy.getcontios.com",
    category: "food",
    tags: ["coffee", "dad", "brother", "foodie", "morning", "ritual", "him"],
    rating: 4.8,
    deliveryDays: 2,
    source: "demo",
  },
  {
    id: "gft_desk_reset",
    title: "Good Desk Day Kit",
    description: "A5 clothbound notebook, smooth rollerball and a tiny desk plant.",
    price: 1799,
    currency: "INR",
    merchant: "Posy demo inventory",
    merchantUrl: "https://posy.getcontios.com",
    category: "stationery",
    tags: ["writing", "tech", "developer", "brother", "colleague", "desk", "practical", "plants"],
    rating: 4.7,
    deliveryDays: 2,
    source: "demo",
  },
  {
    id: "gft_memory_prints",
    title: "Tiny Museum of Us",
    description: "Twelve photo prints in a linen keepsake box, with room for your own captions.",
    price: 2799,
    currency: "INR",
    merchant: "Posy demo inventory",
    merchantUrl: "https://posy.getcontios.com",
    category: "personalized",
    tags: ["romantic", "anniversary", "personalized", "photography", "wife", "partner", "thoughtful"],
    rating: 4.9,
    deliveryDays: 4,
    source: "demo",
  },
  {
    id: "gft_plant_pair",
    title: "Hard-to-Kill Plant Pair",
    description: "Two low-light plants in warm terracotta pots, with honest care cards.",
    price: 1299,
    currency: "INR",
    merchant: "Posy demo inventory",
    merchantUrl: "https://posy.getcontios.com",
    category: "home",
    tags: ["plants", "home", "friend", "housewarming", "cozy", "green"],
    rating: 4.7,
    deliveryDays: 2,
    source: "demo",
  },
  {
    id: "gft_chocolate_note",
    title: "Chocolate, But Personal",
    description: "A small-batch truffle box with a note that sounds like you, not a greeting card.",
    price: 999,
    currency: "INR",
    merchant: "Posy demo inventory",
    merchantUrl: "https://posy.getcontios.com",
    category: "food",
    tags: ["sweet", "treat", "mom", "friend", "anniversary", "indulgent", "foodie"],
    rating: 4.8,
    deliveryDays: 1,
    source: "demo",
  },
  {
    id: "gft_runner_reset",
    title: "Runner's Recovery Mini Kit",
    description: "Performance socks, a massage ball and electrolyte sachets for the next long run.",
    price: 1599,
    currency: "INR",
    merchant: "Posy demo inventory",
    merchantUrl: "https://posy.getcontios.com",
    category: "fitness",
    tags: ["running", "fitness", "brother", "outdoors", "practical", "him"],
    rating: 4.6,
    deliveryDays: 2,
    source: "demo",
  },
];

export function findProduct(id: string): GiftProduct | undefined {
  return CATALOG.find((p) => p.id === id);
}
