import { GiftProduct } from "./types";

// A curated cross-merchant gift catalog. In production this is Prava's
// shop_search across connected merchants (Visa Intelligent Commerce network);
// here it's a realistic stand-in so the demo runs with zero external calls.
export const CATALOG: GiftProduct[] = [
  {
    id: "gft_aromatherapy_set",
    title: "Aromatherapy Diffuser + Essential Oil Set",
    description: "Ceramic ultrasonic diffuser with a 6-oil starter set. Calming, spa-at-home vibe.",
    price: 48,
    merchant: "Vellum Home",
    merchantUrl: "https://vellumhome.example.com",
    category: "wellness",
    tags: ["relaxation", "self-care", "mom", "cozy", "home", "spa"],
    rating: 4.8,
    deliveryDays: 2,
  },
  {
    id: "gft_silk_scarf",
    title: "Hand-Rolled Mulberry Silk Scarf",
    description: "Botanical print, 100% mulberry silk. Gift-boxed with a handwritten card.",
    price: 58,
    merchant: "Maison Lune",
    merchantUrl: "https://maisonlune.example.com",
    category: "fashion",
    tags: ["elegant", "mom", "fashion", "classic", "anniversary", "her"],
    rating: 4.7,
    deliveryDays: 3,
  },
  {
    id: "gft_pourover_kit",
    title: "Pour-Over Coffee Ritual Kit",
    description: "Gooseneck kettle, ceramic dripper, and single-origin beans. For the coffee nerd.",
    price: 72,
    merchant: "Blue Bottle",
    merchantUrl: "https://bluebottlecoffee.com",
    category: "food",
    tags: ["coffee", "dad", "foodie", "morning", "ritual", "him"],
    rating: 4.9,
    deliveryDays: 2,
  },
  {
    id: "gft_mech_keyboard",
    title: "75% Hot-Swap Mechanical Keyboard",
    description: "Gasket-mounted, tactile switches, PBT keycaps. A desk upgrade they'll notice daily.",
    price: 110,
    merchant: "Keychron",
    merchantUrl: "https://keychron.example.com",
    category: "tech",
    tags: ["tech", "gaming", "brother", "developer", "desk", "him", "gadget"],
    rating: 4.6,
    deliveryDays: 4,
  },
  {
    id: "gft_polaroid",
    title: "Instant Camera + Film Bundle",
    description: "Retro instant camera with two film packs. Great for nostalgic, creative types.",
    price: 89,
    merchant: "Fujifilm",
    merchantUrl: "https://fujifilm.example.com",
    category: "tech",
    tags: ["creative", "fun", "sister", "teen", "photography", "nostalgic", "her"],
    rating: 4.5,
    deliveryDays: 3,
  },
  {
    id: "gft_plant_trio",
    title: "Low-Light Houseplant Trio",
    description: "Three easy-care plants in handmade pots. Brightens any apartment.",
    price: 44,
    merchant: "The Sill",
    merchantUrl: "https://thesill.example.com",
    category: "home",
    tags: ["plants", "home", "friend", "housewarming", "cozy", "green"],
    rating: 4.7,
    deliveryDays: 3,
  },
  {
    id: "gft_leather_journal",
    title: "Refillable Leather Journal",
    description: "Full-grain leather, dotted pages, embossed initials on request.",
    price: 52,
    merchant: "Galen Leather",
    merchantUrl: "https://galenleather.example.com",
    category: "stationery",
    tags: ["writing", "thoughtful", "dad", "mentor", "classic", "personalized"],
    rating: 4.8,
    deliveryDays: 5,
  },
  {
    id: "gft_choc_truffles",
    title: "Small-Batch Chocolate Truffle Box",
    description: "24 hand-piped truffles, single-origin cacao. Ships chilled.",
    price: 39,
    merchant: "Compartés",
    merchantUrl: "https://compartes.example.com",
    category: "food",
    tags: ["sweet", "treat", "mom", "her", "anniversary", "indulgent", "foodie"],
    rating: 4.9,
    deliveryDays: 2,
  },
  {
    id: "gft_running_socks",
    title: "Merino Trail Running Sock 3-Pack",
    description: "Cushioned merino blend for runners and hikers. Practical and loved.",
    price: 42,
    merchant: "Smartwool",
    merchantUrl: "https://smartwool.example.com",
    category: "fitness",
    tags: ["running", "fitness", "brother", "outdoors", "practical", "him"],
    rating: 4.6,
    deliveryDays: 3,
  },
  {
    id: "gft_cocktail_kit",
    title: "Craft Cocktail Making Kit",
    description: "Shaker set, bitters, and a recipe book for three signature cocktails.",
    price: 68,
    merchant: "W&P",
    merchantUrl: "https://wandp.example.com",
    category: "food",
    tags: ["cocktails", "entertaining", "friend", "him", "her", "hosting", "fun"],
    rating: 4.5,
    deliveryDays: 4,
  },
  {
    id: "gft_weighted_blanket",
    title: "Cooling Weighted Blanket",
    description: "15 lb, breathable bamboo cover. Better sleep, cozier nights.",
    price: 95,
    merchant: "Bearaby",
    merchantUrl: "https://bearaby.example.com",
    category: "wellness",
    tags: ["cozy", "sleep", "self-care", "mom", "sister", "relaxation", "home"],
    rating: 4.7,
    deliveryDays: 4,
  },
  {
    id: "gft_star_map",
    title: "Custom Night-Sky Star Map",
    description: "A framed print of the stars from a date & place that matters. Deeply personal.",
    price: 64,
    merchant: "Under Lucky Stars",
    merchantUrl: "https://luckystars.example.com",
    category: "personalized",
    tags: ["romantic", "anniversary", "personalized", "her", "him", "thoughtful", "wedding"],
    rating: 4.9,
    deliveryDays: 6,
  },
];

export function findProduct(id: string): GiftProduct | undefined {
  return CATALOG.find((p) => p.id === id);
}
